### ISSUE TITLE
Chatbox is blank

### ISSUE THREAD

**Issue by CodyMKW** [SethClydesdale/forumactif-edge#15]
when I put it at the top or bottom of the homepage its just a blank box is there a way to fix it?
![screenshot at 2017-03-02 02-03-41](https://cloud.githubusercontent.com/assets/8176523/23496533/b555cf56-feec-11e6-80fd-60fcebf03458.png)

**Comment by SethClydesdale** [comment]
Hey,

Can you tell me if the chatbox works on [this test forum](http://themedesign.forumotion.com/login?username=tester&password=demotest&autologin=on&redirect=/forum&query=&login=Log+in) ? The link I provided should automatically log you in to a test account that can use the chatbox.

Also, could you provide the information below ?
- Device the issue occurs on ( e.g. mobile, desktop.. )
- Forum URL
- Was the chatbox working prior to installation ?

**Comment by CodyMKW** [comment]
It doesn't show for me on that test forum

I'm using desktop my forum is http://codysnintendoroom.forumotion.com and it wasn't working when I first installed

**Comment by CodyMKW** [comment]
I'm using Google Chrome I just signed in to my forum with Firefox and it works but it doesn't work on Chrome 

**Edit:** I think I found the problem I disabled extensions one at a time and reloaded the page and when I disabled [MEGA](https://chrome.google.com/webstore/detail/mega/bigefpfhnfcobdlfbedofhhaibnlghod) it works for both the test forum and my forum now

**Comment by SethClydesdale** [comment]
Ah, so it was just an add-on conflicting with the forum then ?

**Comment by CodyMKW** [comment]
yeah seems like it when I removed it the chatbox showed up again

**Comment by SethClydesdale** [comment]
I see, that's good to know for any future issues people might have, even outside of Forumactif Edge. Thanks for letting me know your solution. 😉
