### ISSUE TITLE
Dark Mode for Control Panel

### ISSUE THREAD

**Issue by CodyMKW** [SethClydesdale/forumactif-edge#34]
I think it would be nice if the Control Panel could have a dark theme as well

**Comment by SethClydesdale** [comment]
Hi @CodyMKW,

I agree with your suggestion. I've actually been wanting to implement the selected theme into the control panel's style too. Currently the control panel uses different classes from those that are used in the Dark Mode and Theme Selector CSS, but it's possible to change that. 

I'm gonna add your suggestion to the 1.2.2 milestone.

**Comment by SethClydesdale** [comment]
@CodyMKW The FAE CP should now reflect your selected theme. Let me know if it's working alright on your end. 👍 

![](https://i58.servimg.com/u/f58/18/21/41/30/captur26.png)

**Comment by CodyMKW** [comment]
it looks great working fine for me

**Comment by SethClydesdale** [comment]
Perfect ! 

Thanks for confirming that it's working on your end, and thanks for the suggestion as well. 😉
