### ISSUE TITLE
Install button is not showing

### ISSUE THREAD

**Issue by denethp** [SethClydesdale/forumactif-edge#44]
I tried many times but gives the same erro,r i copied installer.html and paste as the guide says but when i click the eyeball icon it is not showing install button and install options only shows log and faecp version and the description at the top

**Comment by SethClydesdale** [comment]
Hello @Zunehfu,

It sounds like your forum header is not set on the HTML page, which is required for full functionality. Click the edit button (yellow cog icon) next to the preview to edit the HTML page that you created. Once on the edit page, ensure that the option **"Do you wish to use your forum header and footer ?"** is set to **Yes**. Click the **submit** button to save this change, and then go back to HTML pages management and click the preview button (eyeball icon) on the HTML page to go to the control panel on your forum.

If the issue still persists, please let me know.

Have a good day.

**Comment by denethp** [comment]
It's already in that settings but I updated it again to ensure, even it's not working IDK what I'm doing wrong,
I changed my whole skin and version for this but... :()

here's a pic
![12](https://user-images.githubusercontent.com/44388248/47402640-3c1c7700-d764-11e8-8059-415ecbbf4cef.png)

**Comment by SethClydesdale** [comment]
Hi again,

I checked the page and there appears to be no notable technical issues. Just to confirm, are you logged into the [founder account](http://deadly-gangwarz.forumotion.com/u1) ? You must be logged into the founder account to install Forumactif Edge, because Forumotion only allows the founder account to modify the forum templates. If not logged into the founder account, certain options, such as the install button, will be unavailable.

If any concerns, let me know.

Have a good day.

**Comment by denethp** [comment]
Thanks bro fixed

I need to know something can I disable that select theme button for members and put a 1 color for all members.

**Comment by SethClydesdale** [comment]
Hi,

Yes, it's indeed possible to hide or disable the select theme drop down. For the most simple solution, you can hide the theme selector by adding the following CSS rule to your forum's stylesheet. (Admin Panel > Display > Colors > CSS Stylesheet)
```css
a#fae_theme_picker {
  display:none;
}
```

As for changing the default color of the theme, you can do that via [theme management](https://github.com/SethClydesdale/forumactif-edge/wiki/Theme-Management) or [colors](https://github.com/SethClydesdale/forumactif-edge/wiki/Colors). Both of these options can be located in the [FAE Control Panel](https://github.com/SethClydesdale/forumactif-edge/wiki/FAE-Control-Panel-Guide), which is in the HTML page where you previously installed Forumactif Edge.

If anymore questions, let us know.

**Comment by denethp** [comment]
lol also need to vanish darkmode button and keep it always as dark

**Comment by SethClydesdale** [comment]
You can hide the dark mode/light mode switch by adding the following CSS rule to your stylesheet.
```css
#fae_light-switch-container {
  display:none;
}
```

In regards to the forum always being dark, you can change your forum over to a dark theme via theme management (linked in my prior reply). When choosing a theme, select "Edge Dark" to install the dark theme. Also note that your stylesheet will be overwritten when importing a new theme, so please make sure to backup any custom CSS you may have added to the stylesheet.

You can also change the forum colors to something darker via colors management, though I highly recommend theme management for full-scale color changes.

**Comment by denethp** [comment]
Thank you very much

**Comment by SethClydesdale** [comment]
You're welcome.

If you have anymore questions, feel free to let us know by opening a new issue. 😉
