### ISSUE TITLE
Function search

### ISSUE THREAD

**Issue by ghost** [SethClydesdale/forumactif-edge#45]
Hello,

I see a bu in the search menu for the option 
http://waifu.forumactif.com/search

Thx in advance :)

**Comment by ghost** [comment]
It's :
     Rechercher dans les titres des sujets et les contenus des messages
for the first and the second :
     Rechercher dans les titres des sujets

Thx

**Comment by ghost** [comment]
I check the bug tonight and I find the problem :
In your script is : 
`			<dd><label for="any"><input id="any" type="radio" name="search_terms" value="any" checked="checked" /> {L_SEARCH_ANY_TERMS}</label></dd>
			<dd><label for="all"><input id="all" type="radio" name="search_terms" value="all" /> {L_SEARCH_ALL_TERMS}</label></dd>`

And in FA :
`            
			<dd><label for="any"><input id="any" type="radio" name="search_terms" value="any" checked="checked" /> {switch_search_terms.L_SEARCH_ANY_TERMS}</label></dd>
			<dd><label for="all"><input id="all" type="radio" name="search_terms" value="all" /> {switch_search_terms.L_SEARCH_ALL_TERMS}</label></dd>
            `

**Comment by SethClydesdale** [comment]
Hi, thanks for reporting this. It looks like a couple of conditional declarations are missing from the template. The following line is completely missing, for example.
```html
            <!-- BEGIN switch_search_full_text -->
            <dd><label for="text"><input id="text" type="radio" name="search_by" value="text" checked="checked" /> {switch_search_full_text.L_SEARCH_BY_TEXT}</label></dd>
            <dd><label for="subject"><input id="subject" type="radio" name="search_by" value="subject" /> {switch_search_full_text.L_SEARCH_BY_SUBJECT}</label></dd>
            <!-- END switch_search_full_text -->
```

I'll look into it sometime soon and send a patch out to correct it.

**Comment by SethClydesdale** [comment]
Hi again! 

Patch v1.2.13 was just sent out and should correct the issue you reported.

Thanks again for letting me know. 👍

**Comment by ghost** [comment]
Nice Seth !

Thanks for the excellent support :)
