### ISSUE TITLE
SEO optimisation

### ISSUE THREAD

**Issue by ghost** [SethClydesdale/forumactif-edge#46]
Hello Seth,

Are you aware of this FA Update?

https://forum.forumactif.com/t400611-information-nom-d-utilisateur-non-cliquable-pour-les-invites-dans-la-colonne-des-derniers-messages#3343406

Thx in advance

**Comment by SethClydesdale** [comment]
Ah, yes, I saw it a couple days ago. I don't think they made any changes to the templates, correct? I'm assuming the change directly affects `{topics_list_box.row.LAST_POST_AUTHOR}` and other such variables. If the case, there should be nothing to worry about.

**Comment by ghost** [comment]
Yes, thanks for the answer et sorry for the delay.

I think he change anything in forumactif script.
