### ISSUE TITLE
New feature latest

### ISSUE THREAD

**Issue by ghost** [SethClydesdale/forumactif-edge#48]
Hello,

FA add a new feature "Latest"

https://forum.forumactif.com/latest?fbclid=IwAR15D4YPqdrPbPhfummLAYkgJzpaPwwaOsg6qHUkJ6OaWFb2pU0_cNIE3Tc

Can you add in forumactif edge ?

Thanks in advance :)

**Comment by SethClydesdale** [comment]
Hello @DDril,

It looks like it is already functional on Forumactif Edge by accessing "/latest" on your forum.
http://fmdesign.forumotion.com/latest

From what I saw it is for the mobile version. Are you suggesting adding a link to this page? On the index with "View posts since last visit • View your posts • View unanswered posts" perhaps?

**Comment by ghost** [comment]
Sorry for the delay @SethClydesdale 

Yes it's the idea for add in the footer or one button in the header of forum

**Comment by SethClydesdale** [comment]
No problem. I'll look into the possibility of adding it to the templates. Most likely on the index where the other search links are located. 

EDIT:
Probably here:
![](https://i.imgur.com/uxPA6fg.png)
The `{L_LASTPOST}` variable works well for the texts, so fortunately we wont need to add a new alias to the translation files. Before I send out this update, I want to check my todo list to see if there is anything else that needs fixing/updating/adding/etc. If you think of anything else, feel free to let me know.

Thanks for your suggestions and support. ❤️

**Comment by ghost** [comment]
Ok thanks @SethClydesdale ! And the position it's a good idea.

**Comment by SethClydesdale** [comment]
Hi @DDril,

The feature you suggested is now available in [v1.3.0](https://github.com/SethClydesdale/forumactif-edge/releases/tag/v1.3.0).

Thanks again!
